# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GNSS',
            new_name='SatSystem',
        ),
    ]
