# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0002_auto_20181009_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SatSystem',
            new_name='SatelliteSystem',
        ),
    ]
