# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0003_auto_20181009_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
