# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinex', '0006_auto_20181021_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
